### ISSUE TITLE
Changes in the forum and newsletter part are not visible in the page

### ISSUE THREAD

**Issue by SubhrajitPrusty** [codex-iter/codex-iter.github.io#12]
Changes in the forum and newsletter part are not visible in the page in either Github Pages or the 000webhostapp.

**Comment by Zanark** [comment]
The website on 000webhostapp will be updated later when @rupesh1310 completes the home page.
Comming to gihub pages, the home pages is under development.

**Comment by Zanark** [comment]
The changes in the newsletter have been deployed on the website.
The forum will work after I update the database and connect it to the PHP scripts

**Comment by Zanark** [comment]
The forum database has been updated on 000webhostapp
