### ISSUE TITLE
Make the favicon changes

### ISSUE THREAD

**Issue by rupesh1310** [codex-iter/codex-iter.github.io#16]
@Zanark

**Comment by rupesh1310** [comment]
See my recent commits and change. @Zanark  and tell if there is any css problem.

**Comment by Zanark** [comment]
The picture has a white background which is annoying.
Ask amityadyuti bhaiya to provide you with one which has a transparent background.

**Comment by Zanark** [comment]
I made the necessary changes to the favicon and the logo.
