### ISSUE TITLE
Icon and logo are too small

### ISSUE THREAD

**Issue by SubhrajitPrusty** [codex-iter/codex-iter.github.io#17]
Both the favicon and logo are too small and look really bad in mobile displays.

**Comment by Zanark** [comment]
The favicon cannot exceed the current size. You can compare it with GitHub's favicon.
As for the Logo, yes it is small and looks bad, but currently that's the only thing that I could use as a temporary solution.
The changes you made to the icon made the page to load up really slow for some reason.

**Comment by Zanark** [comment]
The logo might look better now.

**Comment by Zanark** [comment]
I honestly don't knowissue has why did the website take a decade to load up but I believe the been solved  now. 
I thank you for helping us out with the logo issue 😄
