### ISSUE TITLE
Default page is set to the last page.

### ISSUE THREAD

**Issue by SubhrajitPrusty** [codex-iter/codex-iter.github.io#9]
When opening the page, the last view is shown first, instead of the first page.
Also, both are named "Home" for some reason.

**Comment by Zanark** [comment]
Yes, @rupesh1310 is currently working on that

**Comment by rupesh1310** [comment]
https://rupesh1310.github.io/codex-newsletter/ @Zanark use this for newsletter when the frontend is changed.

**Comment by Zanark** [comment]
It looks awesome!
Will use it for the newsletter
